/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: f8d512a4d6eedf70298d1efb475bcab0)
interface __BaseEnv_Env {
	CACHE: KVNamespace;
	TEMPLATES: R2Bucket;
	BUSINESS_ASSETS: R2Bucket;
	IMAGES: R2Bucket;
	BUSINESS_IMAGES: R2Bucket;
	DB: D1Database;
	FLAGS: Flagship;
	AI: Ai;
	GOOGLE_CLIENT_ID: "434934291611-9uo1jsbg07dnd711l4vb47kbrm2okoc0.apps.googleusercontent.com";
	CLOUDFLARE_WORKERS_AI_TOKEN: string;
	CLOUDFLARE_AIG_TOKEN: string;
	OPENAI_API_KEY: string;
	HUGGINGFACE_API_KEY: string;
	DEEPGRAM_API_KEY: string;
	CLOUDFLARE_API_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	ADMIN_KEY: string;
	GOOGLE_CLIENT_SECRET: string;
	FACEBOOK_APP_SECRET: string;
	FB_EMAIL: string;
	FB_PASSWORD: string;
	FB_ACCESS_TOKEN: string;
	Chat: DurableObjectNamespace<import("./src/server").Chat>;
	VoiceAgent: DurableObjectNamespace<import("./src/server").VoiceAgent>;
	AtlasLive: DurableObjectNamespace<import("./src/server").AtlasLive>;
	ANALYZER: Fetcher /* kiamichi-biz-ai-analyzer */;
	RAG_AGENT: Fetcher /* purple-snow-f107-nlweb */;
	FACEBOOK_WORKER: Fetcher /* kiamichi-facebook-worker */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat" | "VoiceAgent" | "AtlasLive";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_CLIENT_ID" | "CLOUDFLARE_WORKERS_AI_TOKEN" | "CLOUDFLARE_AIG_TOKEN" | "OPENAI_API_KEY" | "HUGGINGFACE_API_KEY" | "DEEPGRAM_API_KEY" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_ACCOUNT_ID" | "ADMIN_KEY" | "GOOGLE_CLIENT_SECRET" | "FACEBOOK_APP_SECRET" | "FB_EMAIL" | "FB_PASSWORD" | "FB_ACCESS_TOKEN">> {}
}
