/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: c0095abddc711a017ee637679b743b94)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat" | "VoiceAgent";
	}
	interface Env {
		CACHE: KVNamespace;
		GOOGLE_CLIENT_ID: "434934291611-9uo1jsbg07dnd711l4vb47kbrm2okoc0.apps.googleusercontent.com";
		OPENAI_API_KEY: string;
		HUGGINGFACE_API_KEY: string;
		DEEPGRAM_API_KEY: string;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		VoiceAgent: DurableObjectNamespace<import("./src/server").VoiceAgent>;
		TEMPLATES: R2Bucket;
		BUSINESS_ASSETS: R2Bucket;
		IMAGES: R2Bucket;
		DB: D1Database;
		ANALYZER: Fetcher /* kiamichi-biz-ai-analyzer */;
		RAG_AGENT: Fetcher /* purple-snow-f107-nlweb */;
		FACEBOOK_WORKER: Fetcher /* kiamichi-facebook-worker */;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_CLIENT_ID" | "OPENAI_API_KEY" | "HUGGINGFACE_API_KEY" | "DEEPGRAM_API_KEY">> {}
}
