/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 996040beaef9e847fe17712121bca29b)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat" | "VoiceAgent" | "AtlasLive";
	}
	interface Env {
		CACHE: KVNamespace;
		TEMPLATES: R2Bucket;
		BUSINESS_ASSETS: R2Bucket;
		IMAGES: R2Bucket;
		BUSINESS_IMAGES: R2Bucket;
		DB: D1Database;
		AI: Ai;
		GOOGLE_CLIENT_ID: "434934291611-9uo1jsbg07dnd711l4vb47kbrm2okoc0.apps.googleusercontent.com";
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		VoiceAgent: DurableObjectNamespace<import("./src/server").VoiceAgent>;
		AtlasLive: DurableObjectNamespace<import("./src/server").AtlasLive>;
		ANALYZER: Fetcher /* kiamichi-biz-ai-analyzer */;
		RAG_AGENT: Fetcher /* purple-snow-f107-nlweb */;
		FACEBOOK_WORKER: Fetcher /* kiamichi-facebook-worker */;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_CLIENT_ID">> {}
}
